import { useCallback, useEffect, useState } from 'react';
import { active, api, ApiError, usePoll } from './api';
import type { Case, Minimization, Profile, Regression, Run, RunSummary, Side, Suite } from './types';

function ErrorBox({ error }: { error: ApiError | null }) { return error ? <div className="error" role="alert">{error.message}<small>Request ID: {error.requestId ?? 'unavailable (no response)'}</small></div> : null; }
function Chart({ hash, label }: { hash?: string | null; label: string }) { const [failed, setFailed] = useState(false); useEffect(() => setFailed(false), [hash]); return <figure><figcaption>{label}</figcaption>{hash && !failed ? <img src={`/api/artifacts/${hash}`} alt={label} onError={() => setFailed(true)} /> : <p>{failed ? 'Image unavailable. Retry the backend connection.' : 'Image not available yet.'}</p>}</figure>; }
function Evidence({ side, label }: { side: Side; label: string }) { return <article className="evidence"><h3>{label} <span className={`pill ${side.verdict}`}>{side.verdict}</span></h3><Chart hash={side.image_hash} label={`${label} chart`} /><p className="question">{side.question}</p><p>Expected answer: <strong>{JSON.stringify(side.expected_answer)}</strong></p><ol className="observations">{[0, 1, 2].map(slot => { const o = side.observations.find(o => o.slot === slot); return <li key={slot}><strong>Observation {slot + 1} · {o?.status ?? 'not acquired'}</strong>{o ? <><small>{o.model} · {o.provider}</small><small><time>{o.acquired_at}</time> · {o.cached ? 'cached' : 'live acquisition'}</small><pre>{o.raw_text}</pre></> : <p>No successful response acquired for this slot.</p>}</li>; })}</ol></article>; }

export default function App() {
  const [connected, setConnected] = useState(true), [retryCount, setRetryCount] = useState(0), [epoch, setEpoch] = useState(0);
  const [suites, setSuites] = useState<Suite[]>([]), [profiles, setProfiles] = useState<Profile[]>([]), [history, setHistory] = useState<RunSummary[]>([]);
  const [suite, setSuite] = useState(''), [profile, setProfile] = useState(''), [fresh, setFresh] = useState(false), [limit, setLimit] = useState('');
  const [runId, setRunId] = useState<string | null>(null), [viewFresh, setViewFresh] = useState(false), [cases, setCases] = useState<Case[]>([]), [selected, setSelected] = useState<string | null>(null);
  const [info, setInfo] = useState<Case | null>(null), [mid, setMid] = useState<string | null>(null), [saved, setSaved] = useState<Regression | null>(null), [download, setDownload] = useState<string | null>(null);
  const [initializing, setInitializing] = useState(true), [busy, setBusy] = useState(false), [caseLoading, setCaseLoading] = useState(false), [error, setError] = useState<ApiError | null>(null), [caseError, setCaseError] = useState<ApiError | null>(null);
  const fail = useCallback((e: ApiError) => { if (e.offline) { setConnected(false); setRetryCount(n => n + 1); } }, []);
  const run = usePoll<Run>(runId ? `/api/runs/${runId}` : null, connected, epoch, fail);
  const min = usePoll<Minimization>(mid ? `/api/minimizations/${mid}` : null, connected, epoch, fail);
  const loadMetadata = useCallback(async () => { setInitializing(true); try { const [s, p, h] = await Promise.all([api<Suite[]>('/api/suites'), api<Profile[]>('/api/models'), api<RunSummary[]>('/api/runs')]); setSuites(s); setProfiles(p); setHistory(h); const recorded = h.find(r => r.status === 'completed'); if (recorded) { setRunId(old => old ?? recorded.id); setViewFresh(old => old || recorded.fresh); } setSuite(old => old || s[0]?.id || ''); setProfile(old => old || p[0]?.name || ''); setError(null); setConnected(true); setRetryCount(0); } catch (e) { setError(e as ApiError); fail(e as ApiError); } finally { setInitializing(false); } }, [fail]);
  useEffect(() => { void loadMetadata(); }, [loadMetadata]);
  const retry = useCallback(async () => { try { await api('/api/health'); setConnected(true); setEpoch(n => n + 1); await loadMetadata(); } catch (e) { setError(e as ApiError); fail(e as ApiError); } }, [loadMetadata, fail]);
  useEffect(() => { if (connected) return; const timer = window.setTimeout(() => void retry(), Math.min(30000, 2000 * 2 ** Math.min(retryCount, 4))); return () => window.clearTimeout(timer); }, [connected, retryCount, retry]);
  useEffect(() => { if (!runId || !connected) return; let alive = true; void api<Case[]>(`/api/runs/${runId}/cases`).then(c => { if (alive) { setCases(c); setSelected(old => old ?? c.find(row => row.eligible)?.case_id ?? null); setError(null); } }).catch(e => { if (alive) { setError(e); fail(e); } }); return () => { alive = false; }; }, [runId, run.data, connected, epoch, fail]);
  useEffect(() => { setInfo(null); setMid(null); setSaved(null); setCaseError(null); }, [runId, selected]);
  useEffect(() => { if (!runId || !selected || !connected) { setCaseLoading(false); return; } let alive = true; setCaseLoading(true); void api<Case>(`/api/runs/${runId}/cases/${encodeURIComponent(selected)}`).then(c => { if (alive) { setInfo(c); setMid(old => old ?? c.minimization_id); } }).catch(e => { if (alive) { setCaseError(e); fail(e); } }).finally(() => { if (alive) setCaseLoading(false); }); return () => { alive = false; }; }, [runId, selected, connected, epoch, run.data?.status, fail]);
  useEffect(() => { if (!saved) { setDownload(null); return; } const url = URL.createObjectURL(new Blob([JSON.stringify(saved.case, null, 2)], { type: 'application/json' })); setDownload(url); return () => URL.revokeObjectURL(url); }, [saved]);
  const currentSuite = suites.find(s => s.id === suite), currentProfile = profiles.find(p => p.name === profile);
  const families = limit === '' ? currentSuite?.family_count : Number(limit);
  const validLimit = limit === '' || (Number.isInteger(families) && Number(families) >= 1 && Number(families) <= (currentSuite?.family_count ?? 0));
  const working = active(run.data?.status), reducing = active(min.data?.status);
  const chooseRun = (id: string, isFresh: boolean) => { setRunId(id || null); setViewFresh(isFresh); setSelected(null); setCases([]); };
  async function start() { setBusy(true); setError(null); try { const result = await api<{ run_id: string }>('/api/runs', { suite_id: suite, model_profile: profile, fresh, ...(limit ? { limit: Number(limit) } : {}) }); chooseRun(result.run_id, fresh); setEpoch(n => n + 1); } catch (e) { setError(e as ApiError); fail(e as ApiError); } finally { setBusy(false); } }
  async function cancel(kind: 'runs' | 'minimizations', id: string) { setBusy(true); try { await api(`/api/${kind}/${id}/cancel`, {}); setEpoch(n => n + 1); } catch (e) { setError(e as ApiError); fail(e as ApiError); } finally { setBusy(false); } }
  async function minimize() { if (!info || !runId) return; setBusy(true); setCaseError(null); setSaved(null); try { const pair = info.original.verdict === 'passes' && info.transformed.verdict === 'fails'; const result = await api<{ minimization_id: string }>('/api/minimizations', { run_id: runId, case_id: info.case_id, ...(pair ? {} : { side: info.original.verdict === 'fails' ? 'original' : 'transformed' }) }); setMid(result.minimization_id); setEpoch(n => n + 1); } catch (e) { setCaseError(e as ApiError); fail(e as ApiError); } finally { setBusy(false); } }
  async function save() { if (!mid) return; setBusy(true); try { setSaved(await api<Regression>('/api/regressions', { minimization_id: mid })); } catch (e) { setCaseError(e as ApiError); fail(e as ApiError); } finally { setBusy(false); } }
  const cached = run.data?.cached_count ?? cases.reduce((n, c) => n + c.original.cached_count + c.transformed.cached_count, 0), live = run.data?.live_count ?? cases.reduce((n, c) => n + c.original.live_count + c.transformed.live_count, 0);
  const complete = cases.filter(c => c.original.verdict !== 'inconclusive' && c.transformed.verdict !== 'inconclusive').length;
  const inconclusive = cases.filter(c => c.pair_status === 'inconclusive').length;
  const invalid = cases.reduce((n, c) => n + [...c.original.observations, ...c.transformed.observations].filter(o => o.status === 'invalid_output').length, 0);
  const providerErrors = Object.values(run.data?.error_counts ?? run.data?.budget.error_counts ?? {}).reduce((n, value) => n + value, 0);
  const m = min.data, side = m?.side ?? 'original';
  return <main><header><div><span className="eyebrow">OPEN-WEIGHT MODEL EVALUATION</span><h1>CounterFact<span className="dot">.</span></h1><p>Find the failure. Shrink the chart. Keep the evidence.</p></div><span className="connection">{connected ? 'Backend connected' : 'Disconnected'}</span></header>
    {!connected && <div className="banner offline" role="alert"><strong>Backend unreachable. Polling paused.</strong><p>Your last evidence stays visible. Reconnection uses bounded backoff.</p><button onClick={() => void retry()}>Retry connection</button></div>}
    {runId && run.data && live === 0 && !(run.data.fresh ?? history.find(h => h.id === runId)?.fresh ?? viewFresh) && <div className="banner recorded">Recorded run — no live inference{working && <small>Missing cached slots may still dispatch while this run is active. Check the attempt budget.</small>}</div>}
    <section aria-labelledby="run-title"><div className="section-heading"><span className="section-letter">A</span><div><h2 id="run-title">Run</h2><p>Controlled charts, repeated observations, explicit quota.</p></div></div>
      {initializing && <p role="status">Loading suites, profiles and recorded runs…</p>}<ErrorBox error={error ?? run.error} />{(error || run.error) && connected && <button onClick={() => void retry()}>Retry</button>}
      {!initializing && (!suites.length || !profiles.length) && <p>No suites or profiles available. Start the backend and retry.</p>}
      <form onSubmit={e => { e.preventDefault(); void start(); }}><div className="form-grid"><label>Suite<select value={suite} onChange={e => setSuite(e.target.value)} disabled={initializing}>{suites.map(s => <option key={s.id} value={s.id}>{s.id} · {s.family_count} families</option>)}</select></label><label>Model profile<select value={profile} onChange={e => setProfile(e.target.value)} disabled={initializing}>{profiles.map(p => <option key={p.name}>{p.name}</option>)}</select><small>Key present: {currentProfile?.key_present ? 'yes' : 'no'}</small></label><label>Family limit (optional)<input type="number" min="1" max={currentSuite?.family_count} value={limit} onChange={e => setLimit(e.target.value)} placeholder="Entire suite" aria-invalid={!validLimit} /></label></div><label className="checkbox"><input type="checkbox" checked={fresh} onChange={e => setFresh(e.target.checked)} />Fresh acquisition (costs real quota)</label><div className="actions"><button type="submit" disabled={!connected || busy || working || !currentProfile?.key_present || !currentSuite || !validLimit}>Start run</button>{working && runId && <button type="button" className="secondary" disabled={busy || !connected} onClick={() => void cancel('runs', runId)}>Cancel run</button>}<p>{validLimit && families ? `${families * 2 * 3} estimated requests` : 'Select a valid suite and limit'} <small>Upper bound before cache · 2 images × 3 observations; retries add attempts</small></p></div>{!currentProfile?.key_present && <p className="reason">Start disabled: this profile has no backend API key. Configure the local .env file.</p>}{!validLimit && <p className="reason">Limit must be a whole number within the selected suite.</p>}</form>
      <label className="history">View recorded run<select value={history.some(h => h.id === runId) ? runId ?? '' : ''} onChange={e => { const h = history.find(h => h.id === e.target.value); if (h) chooseRun(h.id, h.fresh); }}><option value="">Select a saved run</option>{history.map(h => <option key={h.id} value={h.id}>{h.created_at} · {h.status} · {h.id}</option>)}</select></label>
      {!runId && <p className="empty">Start a run or select recorded evidence above. Nothing is inferred on page load.</p>}
      {run.loading && !run.data && <p role="status">Loading run…</p>}{run.data && <><div className="metrics" aria-live="polite"><div><small>Status</small><strong>{run.data.status}</strong></div><div><small>Completed / inconclusive families</small><strong>{complete} / {inconclusive}</strong></div><div><small>Provider error attempts</small><strong>{providerErrors}</strong></div><div><small>Invalid output observations</small><strong>{invalid}</strong></div><div><small>Cached / live observations</small><strong>{cached} / {live}</strong></div><div><small>Attempts / budget</small><strong>{run.data.budget.used} / {run.data.budget.cap}</strong></div></div>{run.data.message && <p>{run.data.message}</p>}{run.data.error && <p className="error">{run.data.error.message}</p>}{cases.length ? <div className="table-wrap"><table><caption>Click a case to inspect its recorded evidence.</caption><thead><tr><th>Case / question type</th><th>Original</th><th>Transformed</th><th>Pair status</th><th>Cached / live</th></tr></thead><tbody>{cases.map(c => <tr key={c.case_id} className={selected === c.case_id ? 'selected' : ''} onClick={() => setSelected(c.case_id)}><td><button className="case-button" onClick={() => setSelected(c.case_id)} aria-pressed={selected === c.case_id}>{c.case_id}</button><small>{c.question_type}</small></td><td>{c.original.verdict}<small>{c.original.correct_count}/3 correct</small></td><td>{c.transformed.verdict}<small>{c.transformed.correct_count}/3 correct</small></td><td>{c.pair_status}</td><td>{c.original.cached_count + c.transformed.cached_count} / {c.original.live_count + c.transformed.live_count}</td></tr>)}</tbody></table></div> : <p className="empty">No case results saved yet.{working ? ' Waiting for the first observation group.' : ''}</p>}</>}
    </section>
    <section aria-labelledby="investigation-title"><div className="section-heading"><span className="section-letter">B</span><div><h2 id="investigation-title">Failure investigation</h2><p>Source-grounded answers and unedited model responses.</p></div></div><ErrorBox error={caseError ?? min.error} />{(caseError || min.error) && connected && <button onClick={() => void retry()}>Retry investigation</button>}{!selected && <p className="empty">Select a case in the results table to inspect both charts.</p>}{caseLoading && <p role="status">Loading case evidence…</p>}{info && <><h3>{info.case_id}</h3><div className="pair"><Evidence side={info.original} label="Original" /><Evidence side={info.transformed} label="Transformed" /></div><div className="actions"><button disabled={!info.eligible || busy || reducing || !connected || !currentProfile?.key_present} onClick={() => void minimize()}>Minimize failure</button>{reducing && mid && <button className="secondary" disabled={busy || !connected} onClick={() => void cancel('minimizations', mid)}>Cancel minimization</button>}</div>{!info.eligible && <p className="reason">{info.eligibility_reason}</p>}{!currentProfile?.key_present && <p className="reason">Minimization needs the backend model key.</p>}</>}
      {min.loading && !m && <p role="status">Loading minimization…</p>}{m && <div className="reduction"><h3>{m.confirmed ? 'Smallest confirmed case' : 'Smallest observed candidate (unconfirmed)'}</h3><div className="metrics"><div><small>Calls used</small><strong>{m.calls_used} / {m.cap}</strong></div><div><small>Cache hits</small><strong>{m.cache_hits}</strong></div><div><small>Elapsed</small><strong>{m.elapsed}s</strong></div><div><small>Validity rejections</small><strong>{m.validity_rejections}</strong></div><div><small>Current best categories</small><strong>{m.best_candidate.chart.categories.length}</strong></div></div><p>Status: <strong>{m.status}</strong> · Confirmed: <strong>{m.confirmed ? 'yes' : 'no'}</strong> · Terminal reason: <strong>{m.terminal_reason ?? 'not terminal'}</strong></p>{m.error && <p className="error">{m.error.message}</p>}<p className="muted">Attempt budget includes retries. This search does not claim global minimality.</p><div className="pair"><Chart hash={m.artifacts?.[`before_${side}`] ?? info?.[side].image_hash} label="Before reduction" /><Chart hash={m.artifacts?.[`after_${side}`]} label="After reduction" /></div><details open><summary>Reduction steps</summary>{m.steps.length ? <ol className="steps">{m.steps.map(s => <li key={s.sequence}><span className={`pill ${s.valid ? s.accepted ? 'passes' : 'mixed' : 'fails'}`}>{!s.valid ? 'invalid' : s.accepted ? 'accepted' : 'rejected'}</span><strong>{s.phase}</strong>{s.size && <span>{s.size[0]} categories</span>}<small>{s.reason ?? s.candidate_hash}</small></li>)}</ol> : <p>No steps persisted yet.</p>}</details><button disabled={!m.confirmed || busy || reducing || !connected} onClick={() => void save()}>Save regression</button>{saved && <p className="saved">Saved ID: <code>{saved.id}</code> {download && <a href={download} download={`counterfact-${saved.id}.json`}>Download case JSON</a>}</p>}</div>}
    </section><footer>Model comparison: not implemented in this build</footer></main>;
}
